### ISSUE TITLE
Completion does not work

### ISSUE THREAD

**Issue by arwtyxouymz** [coc-extensions/coc-omnisharp#12]
### Problem
Hi, I try to use this extension for C# completion in neovim.
I followed `README.md` instruction but completion doesn't work.

Although I'm not sure that this is related to the completion problem when I open `.cs` file, this message appears
```
[coc.nvim] Source "cs" recreated
```

I don't know what information I should give here so please tell me if needed.

### My Environment
OS: `Ubuntu 18.04`
neovim: `v0.5.0-dev`
dotnet: `3.0.100`
mono: `6.4.0.198`

**Comment by arwtyxouymz** [comment]
I solved this problem.

I didn't create `dotnet` project by `dotnet new` command.
I'm sorry.

**Comment by yatli** [comment]
Hi Ryutaro,

Glad you worked it out. The `source "cs" recreated` message is normal, don't worry.
Let me know if you still have other problems.

**Comment by joshturge** [comment]
I'm getting this problem as well, I've tried generating a dotnet project but it still doesn't work. Is there something I need to put in my coc-settings.json for it to work?

**Comment by b33rcity** [comment]
Also getting `Can't use installed Mono because OmniSharp isn't running on it`, but replying in this thread because I've noticed some extra oddness with `source "cs" recreated`.

When I first open a project, I can open coc's outline. Then the "source recreated" message appears after a few seconds, and the outline stops working until I restart Coc. 

This is a fresh install of coc-omnisharp (literally 20 minutes ago). I have mono 6.8 installed for the system (possibly why the "can't use installed mono" message appears?).

Might be related to #14 , as I'm also having that issue.
