### ISSUE TITLE
FAILURE: "Could not locate '.../.msbuild/Current/Bin/Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll'"

### ISSUE THREAD

**Issue by en3on** [coc-extensions/coc-omnisharp#13]
I have done a clean install of nvim + omnisharp in a WSL container (Debian)

omnisharp is throwing a couple of errors because it can't find certain DLLs in the .msbuild folder.

[Log File](https://pastebin.com/0AW49kaY)

**Comment by kori4r2** [comment]
Any updates/workarounds for this? Still getting the exact same error here

**Comment by yatli** [comment]
Is the file actually there?

There we a few reports now and then, resolved by a re-installation.

**Comment by kori4r2** [comment]
No it isn't. I actually have omnisharp on vs code working properly without the file and I have already reinstalled both mono and coc-omnisharp. The file isn't there, the problem is it shouldn't be trying to find the file anyway, I checked a lot of previous omnisharp versions on the github release history, none of them have those *.resources.dll files the plugin is trying to find.

**Comment by yatli** [comment]
Ha. I updated my installation in WSL and got a repro.

**Comment by yatli** [comment]
Tracking: https://github.com/OmniSharp/omnisharp-roslyn/issues/1742

**Comment by svermeulen** [comment]
Any workaround to this?

**Comment by mikejzx** [comment]
Getting this same issue too, and [#9 ](https://github.com/coc-extensions/coc-omnisharp/issues/9#issue-497944873)

**Comment by toyboot4e** [comment]
Temporaly solution is.. using [omnisharp-vim](https://github.com/OmniSharp/omnisharp-vim) with ALE or Syntastic ;)

**Comment by yatli** [comment]
Fixed!
