### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by Gee19** [coc-extensions/coc-omnisharp#16]
This plugin seemed to be working last time I used it but I am now seeing this output in `:CocInfo` upon loading a `cs` file.

```
## versions

vim version: NVIM v0.5.0-01ff9db63
node version: v13.7.0
coc.nvim version: 0.0.74
term: xterm-kitty
platform: darwin

## Messages
## Output channel: prettier
## Output channel: coc-omnisharp

coc-omnisharp activated.
workspace root=/Users/Gee19/dev/keyboardApi/KeyboardApi

## Output channel: cs

dyld: Library not loaded: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/libintl.8.dylib
  Referenced from: /Users/Gee19/.config/coc/extensions/coc-omnisharp-data/server/bin/mono
  Reason: image not found
/Users/Gee19/.config/coc/extensions/coc-omnisharp-data/server/run: line 28:  4240 Abort trap: 6           "${mono_cmd}" "${omnisharp_cmd}" "$@"
[Info  - 3:43:32 p.m.] Connection to server got closed. Server will restart.
[Error  - 3:43:32 p.m.] /Users/Gee19/.config/coc/extensions/coc-omnisharp-data/server/run exited with code: 134
```

**Comment by wolfspider** [comment]
@Gee19 Yeah, I ran into this as well and seems to be caused by this actually:
[https://github.com/OmniSharp/omnisharp-roslyn/issues/1693](https://github.com/OmniSharp/omnisharp-roslyn/issues/1693)

What I did to keep going for now is find out the version I was running by looking at the contents of this file:

~/.config/coc/extensions/coc-omnisharp-data/downloadinfo.json

In this case it was:
```
{"url":"https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.34.10/omnisharp-osx.zip","version":"v1.34.10","id":23141337,"downloadedTime":1580390967616}
```
and then download the previous release and overwrite all the files in:

~/.config/coc/extensions/coc-omnisharp-data/server

Then it started working again, looks like this is affecting a few different things.

**Comment by yatli** [comment]
I assume this is fixed upstream?

**Comment by Gee19** [comment]
Should be, I haven't used this extension in a while. Closing this.
